---
# tasks file for apache-simple
  - name: Ensure httpd packages are installed
    yum:
      name: "{{ httpd_packages }}"
      state: present
    notify: restart-apache-service

  - name: Ensure latest httpd.conf is present
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify: restart-apache-service
   
  - name: Ensure latest index.html file is present
    template:
      src: templates/index.html.j2
      dest: /var/www/html/index.html

  - name: Ensure httpd is started
    service:
      name: httpd
      state: started
      enabled: yes
